---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: spotter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: gethostname
          image: mikec1233/spotter:minideb
          command:
            - /bin/sh
            - /scripts/get-hostname.sh
          volumeMounts:
            - name: headhostname
              mountPath: /data
            - name: headhostname-script
              mountPath: /scripts
      containers:
        - name: webapp
          image: REGISTRY:443/DOCKER_APP:BUILD_NUMBER
          ports:
            - name: http-port
              containerPort: 3000
          command:
            - /bin/sh
            - -c
          args:
            - export HEAD_NODE_HOSTNAME=$(cat /data/head_node_hostname.txt) &&
              exec npm start
          volumeMounts:
            - name: headhostname
              mountPath: /data
      volumes:
        - name: headhostname
          emptyDir: {}
        - name: headhostname-script
          configMap:
            name: headhostname-script
