apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: worker
        image: REGISTRY:443/DOCKER_APP:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 5000
